% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  english,
  man]{apa6}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Reproducing the analysis of Schroeder and Epley (2015)},
  pdfauthor={Soyeon Lee1},
  pdflang={en-EN},
  pdfkeywords={Voice, Intellect},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% Table formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\begin{center}\begin{threeparttable}}
%   {\end{threeparttable}\end{center}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\begin{center}\begin{ThreePartTable}}{\end{ThreePartTable}\end{center}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% \usepackage{etoolbox}
\makeatletter
\patchcmd{\HyOrg@maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\patchcmd{\HyOrg@maketitle}
  {\section{\protect\normalfont{\@title}}}
  {\section*{\protect\normalfont{\@title}}}
  {}{\typeout{Failed to patch title.}}
\makeatother
\shorttitle{The Sound of Intellect}
\keywords{Voice, Intellect\newline\indent Word count: X}
\DeclareDelayedFloatFlavor{ThreePartTable}{table}
\DeclareDelayedFloatFlavor{lltable}{table}
\DeclareDelayedFloatFlavor*{longtable}{table}
\makeatletter
\renewcommand{\efloat@iwrite}[1]{\immediate\expandafter\protected@write\csname efloat@post#1\endcsname{}}
\makeatother
\usepackage{lineno}

\linenumbers
\usepackage{csquotes}
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
\else
  \usepackage[shorthands=off,main=english]{babel}
\fi

\title{Reproducing the analysis of Schroeder and Epley (2015)}
\author{Soyeon Lee\textsuperscript{1}}
\date{}


\authornote{

Soyeon Lee, Experimental Psychology Student, Brooklyn College of the City of New York.

Correspondence concerning this article should be addressed to Soyeon Lee, 2900 Bedford Ave. E-mail: \href{mailto:soyeon.lee28@bcmail.cuny.edu}{\nolinkurl{soyeon.lee28@bcmail.cuny.edu}}

}

\affiliation{\vspace{0.5cm}\textsuperscript{1} Brooklyn College of the City University of New York}

\abstract{
A reproduction of the analysis for Experiment 4 from Schroeder and Epley (2015).
}



\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

This report reproduces the analysis of Experiment 4 reported in Schroeder and Epley (2015). The citation for the article is:

Schroeder, J., \& Epley, N. (2015). The sound of intellect: Speech reveals a thoughtful mind, increasing a job candidate's appeal. Psychological science, 26(6), 877-891.

The data were downloaded from \url{https://raw.githubusercontent.com/CrumpLab/statisticsLab/master/data/SchroederEpley2015data.csv}

Schroeder and Epley (2015) investigated perception of intellect inferred from speech involved in the hiring process. In Experiment 4, professional recruiters rated hypothetical candidates' intellect, impression, and hiring likeliness based on pitches delivered via either audio or written transcript. This report replicates the authors' analysis of the effects of two conditions (audio vs.~transcript) on the impression and hire rating scores using independent samples t tests.

\hypertarget{methods}{%
\section{Methods}\label{methods}}

\hypertarget{participants}{%
\subsection{Participants}\label{participants}}

There were 39 professional recruiters from Fortune 500 companies.

\hypertarget{material}{%
\subsection{Material}\label{material}}

The authors used three randomly selected candidate pitches from Experiment 1. The pitches were presented to recruiters in the form of either a voice recording or a written transcript.

\hypertarget{procedure}{%
\subsection{Procedure}\label{procedure}}

The recruiters entered their ratings of candidates' pitches on the basis of intellect, impression, and likely to hire rating. Data for impression and likely to hire ratings were analyzed.

\hypertarget{results}{%
\section{Results}\label{results}}

For each dimension (impression and hire), mean rating scores for each condition (transcript and voice) were submitted to independent samples t tests. A descriptive summary of Impression ratings are displayed in Table 1 and Figure 1. A descriptive summary of Hire ratings are displayed in Table 2 and Figure 2.

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:unnamed-chunk-2}Impression Rating samples.}

\begin{tabular}{lll}
\toprule
condition & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{SD}\\
\midrule
transcript & 4.07 & 2.23\\
audio & 5.97 & 1.92\\
\bottomrule
\end{tabular}

\end{threeparttable}
\end{center}

\end{table}

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:unnamed-chunk-2}Likely to Hire Rating samples.}

\begin{tabular}{lll}
\toprule
condition & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{SD}\\
\midrule
transcript & 2.89 & 2.05\\
audio & 4.71 & 2.26\\
\bottomrule
\end{tabular}

\end{threeparttable}
\end{center}

\end{table}

\includegraphics{APAreport_files/figure-latex/unnamed-chunk-3-1.pdf} \includegraphics{APAreport_files/figure-latex/unnamed-chunk-3-2.pdf}

\hypertarget{by-hand-reporting}{%
\subsection{By hand reporting}\label{by-hand-reporting}}

The professional recruiters formed more positive impressions from listening to candidates' pitches(M=5.97,SD=1.92) versus reading them in a script(M=4.07,SD=2.23),t(37)=2.85, p=.007, mean difference=1.89, 95\% CI {[}0.55,3.24{]}. Similarly, recruiters were more likely to hire a candidate when recruiters listened to pitches (M=4.71,SD=2.26), rather than reading them in script (M=2.89,SD=2.06),t(37)=2.62,p=.013, mean difference=1.83, 95\%CI {[}0.41,3.24{]}.

\hypertarget{papaja-reporting}{%
\subsection{Papaja reporting}\label{papaja-reporting}}

The professional recruiters formed more positive impressions from listening to candidates' pitches(M=5.97,SD=1.92) versus reading them in a script(M=4.07,SD=2.23),\(t(37) = 2.85\), \(p = .007\), \(\Delta M = 1.89\), 95\% CI \([0.55\), \(3.24]\). Similarly, recruiters were more likely to hire a candidate when recruiters listened to pitches (M=4.71,SD=2.26), rather than reading them in script (M=2.89,SD=2.06),\(t(37) = 2.62\), \(p = .013\), \(\Delta M = 1.83\), 95\% CI \([0.41\), \(3.24]\).

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

The re-analysis successfully reproduced the analysis reported by Schroeder and Epley (2015), with a minor difference from the original analysis. For p-value report in Hire rating, Schroeder and Epley (2015) reported p\textless.01. The exact p-value obtained in this re-analysis was p=.013.

In the following section, a simulation-based power analysis was performed.

\hypertarget{simulation-based-power-analysis}{%
\subsection{Simulation-based power analysis}\label{simulation-based-power-analysis}}

The design of Experiment 4 was a single-factor, two-level independent measures design with 39 subjects. In each dimension (Impression or Hire rating), mean difference would reveal which of two conditions (voice or transcript) scored higher in their respective rating.\\
Schroeder and Epley (2015) reported d=0.94 in the Impression rating analysis, and d=0.86 in the Hire rating analysis. The power-curve analyses revealed that approximately 0.63 (Figure 3) and 0.50 (Figure 4) of power were needed to detect the effect sizes Schroeder and Epley (2015) reported for Impression and Hire rating, respectively.

\includegraphics{APAreport_files/figure-latex/unnamed-chunk-4-1.pdf} \includegraphics{APAreport_files/figure-latex/unnamed-chunk-4-2.pdf}

\newpage

\hypertarget{references}{%
\section{References}\label{references}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-schroeder_sound_2015}{}%
Schroeder, J., \& Epley, N. (2015). The sound of intellect: Speech reveals a thoughtful mind, increasing a job candidate's appeal. \emph{Psychological Science}, \emph{26}(6), 877--891. \url{https://doi.org/10.1177/0956797615572906}

\endgroup


\end{document}
