---
title: "ReproducibleReportDraft"
author: "Soyeon Lee"
date: "12/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Re-analysis
```{r}
library(papaja)
library(dplyr)
library(ggplot2)
library(tidyverse)

#load data
all_data<-read.csv("SchroederEpley2015data.csv", header=TRUE)
all_data<-all_data%>% rename(condition=ï..CONDITION)

all_data$condition <- as.factor(all_data$condition)
levels(all_data$condition) <- c("transcript","audio")

impression_results<-t.test(all_data[all_data$condition=='audio',]$Impression_Rating,
                           all_data[all_data$condition=='transcript',]$Impression_Rating,
                           var.equal=TRUE)

hire_results<-t.test(all_data[all_data$condition=='audio',]$Hire_Rating,
                     all_data[all_data$condition=='transcript',]$Hire_Rating,
                     var.equal=TRUE)
```

###table of means for each condition
```{r}
sample_means<-all_data%>% 
                    group_by(Impression_Rating,
                             Hire_Rating)%>%
                    summarize(mean_transcript=mean(transcript),
                                mean_audio=mean(audio))
knitr::kable(head(sample_means))